### ISSUE TITLE
Bug in tracking individuals not identical to parent or best mutant

### ISSUE THREAD

**Issue by mbuzdalov** [DE0CH/OLL#17]
Here you compare them by fitness, which is completely wrong.

https://github.com/DE0CH/OLL/blob/2dc1a4a6ad20d610e5d5f7ae7a91813840ba0e47/onell_algs.py#L178

The proper way is to use the size of `locs_xprime`, that is, if we are going to sample an individual with zero changes from the parent, or zero changes from `xprime`, we do not count it.

**Comment by DE0CH** [comment]
Hi. Thanks a lot for the bug report. To be honest, I took this code from @ndangtt without much verification. So, Nguyen, could you please take a look at this?

However, currently, I ported all the relevant functions to rust because it runs a lot faster. I think the line below is how we count the n_evals now. That is, if the child is different from both parent and x prime, we count it. 

https://github.com/DE0CH/OLL/blob/2dc1a4a6ad20d610e5d5f7ae7a91813840ba0e47/onell_algs_rs/src/lib.rs#L206

I remember when ported the code, I did a (preliminary) empirical analysis to see that the two algorithms are identical. Turns out they were identical. But I might have missed something.

**Comment by ndangtt** [comment]
@mbuzdalov: Hi Maxim, thank you for checking the code! 

Deyao and I have a look at the issue but we're not sure why this is a bug. The first `if` uses the fitness as it's a cheaper way to recognise if `child != parents`, if that doesn't work then we go for the second check, which is more expensive but more accurate. 
https://github.com/DE0CH/OLL/blob/2dc1a4a6ad20d610e5d5f7ae7a91813840ba0e47/onell_algs.py#L180
That one makes sure that the child is different from both `x` and `xprime`. 

Would that make sense to you? Or is there anything that I miss?

**Comment by mbuzdalov** [comment]
Ah, I need to sleep more. That makes sense.
